// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NetModels
{

public enum CommandType : int
{
  Pause = 0,
  Resume = 1,
  NextInstruction = 2,
  SkipInstruction = 3,
};


}
