// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NetModels
{

public enum EventType : int
{
  None = 0,
  EnteredProcedure = 1,
  LeaveProcedure = 2,
  Log = 3,
};


}
